# Application name
spring.application.name=Billing_And_Inventry_Mgmt_System

# Server port (optional - default is 8080)
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/billing_inventory
spring.datasource.username=root
spring.datasource.password=atharv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
